#!/bin/bash
# Run this script to start Ralph with the full AutoWebsites Pro prompt

PROMPT='Build AutoWebsites Pro sales system in /Users/andrewferguson/autowebsites. ANTHROPIC_API_KEY, SUPABASE, SENDGRID in .env. Create 45 files: PHASE 1 AI (5 files): src/ai/claude-client.ts - Anthropic SDK with retry. src/ai/website-analyzer.ts - Claude analyzes HTML, detects industry, finds problems. src/ai/pitch-generator.ts - personalized email per business. src/ai/objection-handler.ts - responses to objections. src/ai/industry-templates.ts - templates for plumbers, lawyers, restaurants, dentists, contractors, HVAC, salons, doctors, accountants, realtors. PHASE 2 CRM (7 files): src/crm/lead-model.ts - enhanced lead with pipeline stages. src/crm/pipeline-manager.ts - stage transitions. src/crm/proposal-generator.ts - PDF proposals with pricing. src/crm/contract-generator.ts - contract templates. src/crm/payment-handler.ts - Stripe test mode. src/crm/activity-logger.ts - interaction timeline. src/db/schema-v2.sql - all tables. PHASE 3 EMAIL (5 files): src/email/composer.ts - MJML templates. src/email/sequence-engine.ts - conditional sequences. src/email/webhook-handler.ts - SendGrid webhooks. src/email/analytics.ts - email metrics. src/email/unsubscribe.ts - CAN-SPAM compliance. PHASE 4 DASHBOARD (12 files): src/dashboard/server.ts - Express with auth. src/dashboard/auth.ts - JWT login. src/dashboard/routes/leads.ts, campaigns.ts, proposals.ts, analytics.ts - API routes. src/dashboard/public/index.html - metrics dashboard. src/dashboard/public/leads.html - lead list. src/dashboard/public/lead-detail.html - lead view. src/dashboard/public/campaigns.html - campaigns. src/dashboard/public/js/app.js - frontend JS. src/dashboard/public/css/styles.css - modern CSS. PHASE 5 UTILS (5 files): src/utils/error-handler.ts, logger.ts, config.ts, validation.ts, health.ts. PHASE 6 INTEGRATION (5 files): src/orchestrator.ts - full pipeline. src/worker.ts - background jobs. src/index.ts - main entry. Update cli.ts and package.json. Install deps: @anthropic-ai/sdk express jsonwebtoken bcryptjs zod stripe pdfkit winston. Test E2E on plumbers Austin TX. Dashboard must run at localhost:3001. Output AUTOWEBSITES_PRO_COMPLETE when all works.'

echo "Starting Ralph Loop with AutoWebsites Pro prompt..."
echo "Prompt length: ${#PROMPT} characters"
echo ""
echo "Run this command in Claude Code:"
echo ""
echo "/ralph-loop:ralph-loop \"$PROMPT\" --completion-promise \"AUTOWEBSITES_PRO_COMPLETE\" --max-iterations 200"
